export const USER_SIGNUP = "USER_SIGNUP";
export const USER_SIGNIN = "USER_SIGNIN";
export const BALANCE_TRANSFER = "BALANCE_TRANSFER";
export const BALANCE_DEPOSIT = "BALANCE_DEPOSIT";
export const VIEW_STATEMENT = "VIEW_STATEMENT";